version: '3'

services:
  database:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "pract12"
      POSTGRES_PASSWORD: admin

    ports:
      - 5435:5432

  web:
    image: py-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database